/*
 * To change this template, c
 @Override
 public int getSize() {
 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 }

 @Override
 public int getSize() {
 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 }

 @Override
 public Object getElementAt(int index) {
 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
 }
 hoose Tools | Templates
 * and open the template in the editor.
 */
package jogosueca.cliente;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author francisco
 */
public class JPanelPontuacoes extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPontuacoes
     */
    public JPanelPontuacoes(ArrayList<String> lista) {
        this.lista = lista;
        initComponents();
        criaLM();
    }

    public void addBtOkActionListener(ActionListener al) {
        jButOkJV.addActionListener(al);
    }

    public void setPontosEquipas(int eq0, int eq1) {
        jLEq0JVR.setText(eq0 + "");
        jLEq1JVR.setText(eq1 + "");
    }

    public JButton getSourceActionListener() {
        return jButOkJV;
    }

    public JList<String> getJlist() {
        return jListJogosVencidos;
    }

    private void criaLM(){
        jListJogosVencidos.setModel(new AbstractListModel() {

            @Override
            public int getSize() {
                return lista.size();
            }

            @Override
            public Object getElementAt(int index) {
                return lista.get(index);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLPontuacao = new javax.swing.JLabel();
        jLEq0JV = new javax.swing.JLabel();
        jLEq1JV = new javax.swing.JLabel();
        jButOkJV = new javax.swing.JButton();
        jScrollPaneJV = new javax.swing.JScrollPane();
        jListJogosVencidos = new javax.swing.JList();
        jLJogosVencidos = new javax.swing.JLabel();
        jLEq0JVR = new javax.swing.JLabel();
        jLEq1JVR = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLPontuacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPontuacao.setText("Pontuação");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLPontuacao, gridBagConstraints);

        jLEq0JV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEq0JV.setText("Equipa 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLEq0JV, gridBagConstraints);

        jLEq1JV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEq1JV.setText("Equipa 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLEq1JV, gridBagConstraints);

        jButOkJV.setText("Ok");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jButOkJV, gridBagConstraints);

        jScrollPaneJV.setViewportView(jListJogosVencidos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPaneJV, gridBagConstraints);

        jLJogosVencidos.setText("Jogos vencidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(jLJogosVencidos, gridBagConstraints);

        jLEq0JVR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEq0JVR.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLEq0JVR, gridBagConstraints);

        jLEq1JVR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEq1JVR.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLEq1JVR, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButOkJV;
    private javax.swing.JLabel jLEq0JV;
    private javax.swing.JLabel jLEq0JVR;
    private javax.swing.JLabel jLEq1JV;
    private javax.swing.JLabel jLEq1JVR;
    private javax.swing.JLabel jLJogosVencidos;
    private javax.swing.JLabel jLPontuacao;
    private javax.swing.JList jListJogosVencidos;
    private javax.swing.JScrollPane jScrollPaneJV;
    // End of variables declaration//GEN-END:variables
    ArrayList<String> lista;
}
